In [1]:
import numpy as np

# Array Attribute'ları

# Shape

In [2]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [3]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [4]:
x.shape

(2, 3)

In [5]:
y.shape

(2, 5, 4)

# ndim

In [6]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [8]:
x.ndim

2

In [9]:
y.ndim

3

# Size

In [10]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
y = np.zeros((2,5,4))

print(y)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [12]:
x.size

6

In [13]:
y.size

40

# Dtype

In [14]:
x = np.zeros((2,3))

print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
x.dtype

dtype('float64')

In [16]:
x=np.zeros((3,4))

In [17]:
x.ndim

2

In [18]:
x.size

12