In [1]:
import numpy as np

# Concatenation

In [3]:
a = np.array([1, 2, 3, 4])

In [5]:
b = np.array([5, 6, 7, 8])

In [6]:
a

array([1, 2, 3, 4])

In [7]:
b

array([5, 6, 7, 8])

In [8]:
# a veya b güncellenmez
np.concatenate([a, b])

array([1, 2, 3, 4, 5, 6, 7, 8])

* python listlerini de numpy arraylari ile concatenation'a sokabiliriz

In [9]:
l = [10, 11]

In [10]:
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

In [11]:
l = [10, 11, 11.2]

In [12]:
np.concatenate([a, b, l])

array([ 1. ,  2. ,  3. ,  4. ,  5. ,  6. ,  7. ,  8. , 10. , 11. , 11.2])

In [13]:
l = [10, 11, "11.2"]

In [14]:
np.concatenate([a, b, l])

array(['1', '2', '3', '4', '5', '6', '7', '8', '10', '11', '11.2'],
      dtype='<U21')

* python tuple'larını da numpy arraylari ile concatenation'a sokabiliriz

In [15]:
l = (10, 11)

In [16]:
np.concatenate([a, b, l])

array([ 1,  2,  3,  4,  5,  6,  7,  8, 10, 11])

# Size Mismatch

In [18]:
a

array([1, 2, 3, 4])

In [19]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])

In [20]:
x.size

6

In [21]:
a.shape

(4,)

In [22]:
# shape mismatch
np.concatenate([x,a])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.concatenate([x,x])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
np.concatenate([x,x], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])