In [1]:
import numpy as np

# Sorting

In [2]:
a = np.array([20, 32, 5, 30, 10])

In [3]:
a

array([20, 32,  5, 30, 10])

In [4]:
np.sort(a)

array([ 5, 10, 20, 30, 32])

In [5]:
a

array([20, 32,  5, 30, 10])

In [6]:
# a yı günceller
a.sort()  # inplace(a = np.sort(a) ile aynı)

In [7]:
a

array([ 5, 10, 20, 30, 32])

# argsort

In [9]:
a = np.array([3,1,6,5,4,2])

In [10]:
# küçükten büyüğe sıralanmış elemanları indexlerini döndürür
idxs = np.argsort(a)

In [11]:
idxs

array([1, 5, 0, 4, 3, 2])