In [1]:
import numpy as np

# Multidimensional Arraylerin Elemanlarına Ulaşmak

In [2]:
a = np.arange(1,21).reshape(4,5)

In [3]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [4]:
a[0]

array([1, 2, 3, 4, 5])

In [5]:
a[1]

array([ 6,  7,  8,  9, 10])

In [6]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
a[0,0]

1

In [8]:
a[0]a[0]

SyntaxError: invalid syntax (2063046774.py, line 1)

In [9]:
a[1,1]

7

In [11]:
a[0,1]

2

In [12]:
a.ndim

2

In [13]:
a[0]

array([1, 2, 3, 4, 5])

In [14]:
a[0].ndim

1

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
a[1,1] = 10

In [17]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 10,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [18]:
# Array'in veri tipi neyse ona cast olur, array in veri tipini dönüştürmez!
a[1,1] = 20.40

In [19]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 20,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [20]:
a[1,1] = "30"

In [21]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [22]:
a[1,1] = "30.5"

ValueError: invalid literal for int() with base 10: '30.5'

In [23]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6, 30,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

# Slice Indexing

In [24]:
a = np.arange(1,21).reshape(4,5)

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
a[1]

array([ 6,  7,  8,  9, 10])

In [27]:
a[0:3]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [28]:
a[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [29]:
a[:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [31]:
a[1:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [32]:
a[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [33]:
a[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [34]:
a[1::2]

array([[ 6,  7,  8,  9, 10],
       [16, 17, 18, 19, 20]])

In [35]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [36]:
a[2,3]

14

In [37]:
# bütün rowları al ama sadece 3. indexteki column u al
a[:,3]

array([ 4,  9, 14, 19])

In [39]:
a[::2,3]

array([ 4, 14])

In [40]:
a[0, :]

array([1, 2, 3, 4, 5])

In [41]:
a[0]

array([1, 2, 3, 4, 5])

In [42]:
a[0, 2:4]

array([3, 4])

In [43]:
a[:2, :3]

array([[1, 2, 3],
       [6, 7, 8]])

In [44]:
a[0:2, 0:3]

array([[1, 2, 3],
       [6, 7, 8]])

In [45]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [46]:
a[::,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [47]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [11, 12, 13, 14],
       [16, 17, 18, 19]])

In [50]:
b=np.arange(1,13).reshape(3,4)

In [51]:
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
b[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])