In [2]:
import numpy as np

In [3]:
a=np.arange(1,21).reshape(4,5)

In [4]:
s = np.sum(a,axis=0)

In [5]:
s.shape

(5,)

In [6]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [7]:
s

array([34, 38, 42, 46, 50])

# sum

* Verilen Condition'ı kaç elemanın sağladığını bulalım

In [8]:
a=np.arange(1,21).reshape(4,5)

In [9]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [10]:
np.sum(a)

210

In [11]:
filt = a < 5

In [12]:
filt

array([[ True,  True,  True,  True, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [13]:
np.sum(filt)

4

In [14]:
a[filt]

array([1, 2, 3, 4])

In [15]:
np.sum(a[filt])

10

In [16]:
filt = (a>5) & (a<9)

In [17]:
np.sum(filt)

3

In [18]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [19]:
a[filt]

array([6, 7, 8])

In [20]:
np.sum(a[(a>5) & (a<9)])

21

In [21]:
filt = ~((a>5) & (a<9))

In [22]:
a[filt]

array([ 1,  2,  3,  4,  5,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [23]:
np.sum(~((a>5) & (a<9)))

17

In [24]:
np.sum(a[~((a>5) & (a<9))])

189

# Belirli axis Üzerinde Toplama

In [25]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [26]:
np.sum(a, axis = 0)

array([34, 38, 42, 46, 50])

In [27]:
np.sum(a, axis = 1)

array([15, 40, 65, 90])

In [28]:
np.sum(a)

210