In [1]:
import numpy as np

# All

* Tüm elemanlar verilen şartı sağlıyor mu kontrol etmek

In [4]:
a = np.arange(20).reshape(4,5)

In [5]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [6]:
a > -1

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [7]:
np.all(a>-1)

True

In [8]:
filt = a > -1

In [9]:
np.all(filt)

True

In [10]:
np.all(a>-1, axis=1)

array([ True,  True,  True,  True])

In [11]:
np.all(a>-1, axis=0)

array([ True,  True,  True,  True,  True])

In [12]:
a > 4

array([[False, False, False, False, False],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
np.all(a>4)

False

In [14]:
a=np.arange(1,21).reshape(4,5)

In [15]:
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [16]:
np.all(a>8,axis=1)

array([False, False,  True,  True])