In [1]:
import numpy as np

# Normal Distribution'dan Çekilmiş Değerler İle Array Oluşturmak

* (mean, std, array size)   ((mean->ortalama, std->standart sapma, arraysize->boyutu))

In [2]:
np.random.normal(0, 1, (4,5))

array([[-0.81233338, -1.76076605,  0.07060115,  0.28842932, -1.2993042 ],
       [ 0.03963054, -0.09562634, -0.73266551,  0.35633386,  0.25755967],
       [ 1.34803451,  0.76382809,  0.64965191,  1.20505967,  1.4148408 ],
       [ 1.17012726, -0.24506832, -0.75287926,  0.37128256,  0.40337004]])

In [3]:
np.random.normal(0, 100, (4,5))

array([[  44.51964402,   27.38199042,  -33.89258957,   62.14657167,
         115.10482252],
       [  16.16294689,  -29.42454623, -167.91967343,   48.67571077,
          18.80417928],
       [-111.44331312, -108.02035507,  -53.27119247,  -67.21825918,
          51.65915241],
       [-143.71839076,  -43.15677544,  -37.83809304,  -36.74924422,
         -81.05709594]])

In [4]:
np.random.normal(10, 100, (4,5))

array([[-73.84815639,  44.70056383, -85.34569316,  66.02653941,
        156.84353532],
       [172.26056047, 101.08152953,  31.96676309,   8.0879912 ,
         64.98721923],
       [166.40838293,  -8.06729445, 135.15494606,   2.22653039,
        114.94027013],
       [ 15.38069018, -21.63871674, -96.33187974, -52.24166363,
        122.39234881]])

In [5]:
np.random.normal(10, 1, (4,5))

array([[10.39756363,  9.13954397,  8.96038712, 10.42827479,  9.95777099],
       [ 9.21415986,  8.43130195,  9.52925386,  9.16848982,  8.4284713 ],
       [ 9.24294623, 10.61012245, 10.56034089, 10.38509001, 10.32602284],
       [ 8.2617816 , 11.15364532, 11.62768871,  9.85696504,  9.37862586]])