In [1]:
import numpy as np

# Reshaping

* Önemli nokta reshape yapacağımız yapının yaptıktan sonraki yapıyla aynı eleman sayısına sahip olması. Yani size'ları aynı olacak

In [2]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a.ndim

1

In [4]:
a.size

10

In [5]:
a.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
a.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [7]:
a.reshape(2,5).ndim

2

* Eleman sayısı tutmazsa hata alırım.

In [8]:
a.reshape(6,2)

ValueError: cannot reshape array of size 10 into shape (6,2)

# -1 ile Boyuta Karar Vermek

In [9]:
a.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

# Yeni Boyut Eklemek

In [10]:
a = np.arange(1,11)

In [16]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
a[np.newaxis, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [12]:
a[np.newaxis, :].shape

(1, 10)

In [13]:
# column vector

a[:, np.newaxis]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [14]:
a[:, np.newaxis].shape

(10, 1)

In [15]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

* Veya None yazarak yapabiliriz

In [17]:
a[None, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [18]:
a[:, None]

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [19]:
a=np.arange(1,7)

In [20]:
x=a[np.newaxis,:]

In [21]:
x.shape

(1, 6)