In [1]:
import numpy as np

# Splitting

In [2]:
l = [10, 20, 30, 40, 50, 60, 70, 80]

In [3]:
l

[10, 20, 30, 40, 50, 60, 70, 80]

In [4]:
# [0,1],[2,3,4,5],[6,7]
np.split(l, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

In [5]:
np.split(l, [3,5])

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80])]

In [6]:
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])

In [7]:
np.split(a, [2,6])

[array([10, 20]), array([30, 40, 50, 60]), array([70, 80])]

# Split'in Sonucunu Birden Çok Değişkene Eşitleme

In [8]:
a, b = (1, 10)

In [10]:
print(a)
print(b)

1
10


In [11]:
x, y, z = np.split(l, [2,6])

In [12]:
print(x)
print(y)
print(z)

[10 20]
[30 40 50 60]
[70 80]


# vsplit

In [13]:
a = np.arange(20).reshape(2,10)

In [14]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [15]:
np.vsplit(a,[1])

[array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]),
 array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])]

In [16]:
np.vsplit(a,[1])[0]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

# hsplit

In [17]:
a = np.arange(20).reshape(2,10)

In [18]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [19]:
np.hsplit(a,[2])

[array([[ 0,  1],
        [10, 11]]),
 array([[ 2,  3,  4,  5,  6,  7,  8,  9],
        [12, 13, 14, 15, 16, 17, 18, 19]])]

In [20]:
np.hsplit(a,[2])[0]

array([[ 0,  1],
       [10, 11]])

In [21]:
np.hsplit(a,[2])[1]

array([[ 2,  3,  4,  5,  6,  7,  8,  9],
       [12, 13, 14, 15, 16, 17, 18, 19]])

In [22]:
np.hsplit(a,[2])[0].shape

(2, 2)

In [23]:
np.hsplit(a,[2])[1].shape

(2, 8)

In [24]:
x, y = np.hsplit(a,[2])

In [25]:
print(x)

[[ 0  1]
 [10 11]]


In [26]:
print(y)

[[ 2  3  4  5  6  7  8  9]
 [12 13 14 15 16 17 18 19]]


In [27]:
x,y,z = np.hsplit(a,[2,4])

In [28]:
print(x)

[[ 0  1]
 [10 11]]


In [29]:
print(y)

[[ 2  3]
 [12 13]]


In [30]:
print(z)

[[ 4  5  6  7  8  9]
 [14 15 16 17 18 19]]


In [31]:
a=np.arange(20).reshape(5,4) 
np.vsplit(a,[2,3]) 

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]