In [2]:
import numpy as np

# Array Data Tipini Manuel Belirtmek

* Array'in elemanlarının tipinin ne olacağını özellikle belirtebiliriz.

In [3]:
x = np.array([1,2,3,4.6])

In [4]:
x

array([1. , 2. , 3. , 4.6])

In [5]:
x = np.array([1,2,3,4.6], dtype = "int32")

In [6]:
x

array([1, 2, 3, 4], dtype=int32)

In [7]:
x = np.array([1,2,3,4.6], dtype = "str")

In [8]:
x

array(['1', '2', '3', '4.6'], dtype='<U3')

In [9]:
x = np.array(["a"], dtype = "int32")

ValueError: invalid literal for int() with base 10: 'a'

In [10]:
x = np.array(["5"], dtype = "int32")

In [11]:
x

array([5], dtype=int32)

In [12]:
x=np.array(["4.2"],dtype="int32")

ValueError: invalid literal for int() with base 10: '4.2'