In [1]:
import numpy as np

# Aralığı Eşit Uzaklıktaki Noktalara Bölmek

* Belirlenen [başlangıç, bitiş] değerine göre, başlangıç ve bitişi dahil edecek şekilde, aralığı eşit uzaklıkta noktalara bölmeyi göreceğiz.

In [2]:
# Default olarak 50 nokta döndürür.
np.linspace(1,2)

array([1.        , 1.02040816, 1.04081633, 1.06122449, 1.08163265,
       1.10204082, 1.12244898, 1.14285714, 1.16326531, 1.18367347,
       1.20408163, 1.2244898 , 1.24489796, 1.26530612, 1.28571429,
       1.30612245, 1.32653061, 1.34693878, 1.36734694, 1.3877551 ,
       1.40816327, 1.42857143, 1.44897959, 1.46938776, 1.48979592,
       1.51020408, 1.53061224, 1.55102041, 1.57142857, 1.59183673,
       1.6122449 , 1.63265306, 1.65306122, 1.67346939, 1.69387755,
       1.71428571, 1.73469388, 1.75510204, 1.7755102 , 1.79591837,
       1.81632653, 1.83673469, 1.85714286, 1.87755102, 1.89795918,
       1.91836735, 1.93877551, 1.95918367, 1.97959184, 2.        ])

# Kaç Parçaya Böleceğini Belirtmek

In [3]:
np.linspace(1,2,num=3)

array([1. , 1.5, 2. ])

In [4]:
np.linspace(1,2,3)

array([1. , 1.5, 2. ])

In [5]:
np.linspace(1,2,num=3,endpoint=False)

array([1.        , 1.33333333, 1.66666667])

In [6]:
# 0 ile 1 arasında (0-1 dahil olacak şekilde) 30 nokta üretmek
np.linspace(0,1,30)

array([0.        , 0.03448276, 0.06896552, 0.10344828, 0.13793103,
       0.17241379, 0.20689655, 0.24137931, 0.27586207, 0.31034483,
       0.34482759, 0.37931034, 0.4137931 , 0.44827586, 0.48275862,
       0.51724138, 0.55172414, 0.5862069 , 0.62068966, 0.65517241,
       0.68965517, 0.72413793, 0.75862069, 0.79310345, 0.82758621,
       0.86206897, 0.89655172, 0.93103448, 0.96551724, 1.        ])

* float'ları da belirtilen sayıda bölebiliyoruz.

In [7]:
np.linspace(1.5, 4.7, 3)

array([1.5, 3.1, 4.7])

In [8]:
np.linspace(1,30)

array([ 1.        ,  1.59183673,  2.18367347,  2.7755102 ,  3.36734694,
        3.95918367,  4.55102041,  5.14285714,  5.73469388,  6.32653061,
        6.91836735,  7.51020408,  8.10204082,  8.69387755,  9.28571429,
        9.87755102, 10.46938776, 11.06122449, 11.65306122, 12.24489796,
       12.83673469, 13.42857143, 14.02040816, 14.6122449 , 15.20408163,
       15.79591837, 16.3877551 , 16.97959184, 17.57142857, 18.16326531,
       18.75510204, 19.34693878, 19.93877551, 20.53061224, 21.12244898,
       21.71428571, 22.30612245, 22.89795918, 23.48979592, 24.08163265,
       24.67346939, 25.26530612, 25.85714286, 26.44897959, 27.04081633,
       27.63265306, 28.2244898 , 28.81632653, 29.40816327, 30.        ])